<?php
namespace App\Repository;


use App\Entity\Cart;
use Jan\Component\Database\Contracts\QueryManagerInterface;
use Jan\Component\Database\ORM\EntityRepository;


/**
 * Class CartRepository
 * @package App\Repository
 *
 * <Generated By JFramework>
*/
class CartRepository extends EntityRepository
{

    /**
     * UserRepository constructor.
     * @param QueryManagerInterface $manager
    */
    public function __construct(QueryManagerInterface $manager)
    {
        parent::__construct($manager, Cart::class);
    }
}