<?php
namespace App\Repository;


use App\Entity\Post;
use Jan\Component\Database\Contracts\QueryInterface;
use Jan\Component\Database\ORM\EntityRepository;


/**
 * Class PostRepository
 * @package App\Repository
 *
 * <Generated By JFramework>
*/
class PostRepository extends EntityRepository
{

    /**
     * PostRepository constructor.
     * @param QueryInterface $manager
     * @throws \ReflectionException
    */
    public function __construct(QueryInterface $manager)
    {
        parent::__construct($manager, Post::class);
    }
}