<?php
namespace App\Repository;


use App\Entity\Post;
use Jan\Component\Database\Contracts\QueryManagerInterface;
use Jan\Component\Database\ORM\EntityRepository;


/**
 * Class PostRepository
 * @package App\Repository
 *
 * <Generated By JFramework>
*/
class PostRepository extends EntityRepository
{

    /**
     * UserRepository constructor.
     * @param QueryManagerInterface $manager
    */
    public function __construct(QueryManagerInterface $manager)
    {
        parent::__construct($manager, Post::class);
    }
}