<?php
namespace App\Controllers\Form;


use App\Controllers\BaseController;
use App\Services\SimpleEmailSender;
use Jan\Component\Database\Connection;
use Jan\Component\Http\Request;
use Jan\Component\Http\Response;
use Jan\Component\Templating\Exceptions\ViewException;
use Jan\Services\Session\Session;


/**
 * Class BadWayFormController
 * @package App\Controllers\Form
 *
 * <Generated By JFramework>
*/
class BadWayFormController extends BaseController
{

    /**
     * @param Request $request
     * @param SimpleEmailSender $emailSender
     * @return Response
     * @throws ViewException
     */
     public function index(Request $request, SimpleEmailSender $emailSender): Response
     {
          $emails = [
             'contact@local.dev',
             'depannage@local.dev',
             'shell@local.dev'
          ];

          $errors = $this->validationLogic($_POST, $emails);

          // has errors
          if(! empty($errors))
          {
              Session::put('errors', $errors);
              Session::put('inputs', $_POST);
              header('Location: '. route('gk.service.form'));

          } else{

              // Email
              $message = $request->post('message');
              $service = $request->post('service');
              $email = $request->post('email');
              $name = $request->post('name');

              $headers = 'FROM: '. $email;

              if($emailSender->send($emails[$service], 'Formulaire de contact de '. $name, $message, $headers))
              {
                  echo 'Send OK';
              }else{
                  echo 'No sent';
              }
              Session::put('success', 1);
              header('Location: '. route('app.home'));
          }

          return $this->render('form/form.phtml', compact('emails'));
     }


    /**
     * @param array $data
     * @param array $options
     * @return array
     */
     protected function validationLogic(array $data, array $options = [])
     {
         $errors = [];

         // Text
         if(! array_key_exists('name', $data) || $data['name'] == '')
         {
             $errors['name'] = "Vous n'avez pas renseigne votre nom";
         }

         // Email
         if(! array_key_exists('email', $data) || $data['email'] == '' || ! filter_var($data['email'], FILTER_VALIDATE_EMAIL))
         {
             $errors['email'] = "Vous n'avez pas renseigne un email valid";
         }

         // Textarea
         if(! array_key_exists('message', $data) || $data['message'] == '')
         {
             $errors['message'] = "Vous n'avez pas ajouter de message";
         }

         // Select (Options)
         if(! array_key_exists('service', $data) || ! isset($options[$data['service']]))
         {
             $errors['service'] = 'Le service que vous demandez n\' existe pas';
         }

         return $errors;
     }
}