<?php
namespace App\Controllers\Form;


use App\Controllers\BaseController;
use App\Services\SimpleEmailSender;
use Jan\Component\Database\Connection;
use Jan\Component\Http\Request;
use Jan\Component\Http\Response;
use Jan\Component\Templating\Exceptions\ViewException;
use Jan\Services\Form\Form;
use Jan\Services\Session\Session;
use Jan\Services\Validation\Validator;


/**
 * Class FormController
 * @package App\Controllers
 *
 * <Generated By JFramework>
*/
class FormController extends BaseController
{

    /**
     * @param Request $request
     * @param SimpleEmailSender $emailSender
     * @return Response
     * @throws ViewException
     */
     public function index(Request $request, SimpleEmailSender $emailSender): Response
     {
          $emails = [
             'contact@local.dev',
             'depannage@local.dev',
             'shell@local.dev'
          ];

          $validator = new Validator($request->post());
          $validator->check('name', 'required');
          $validator->check('email', 'required');
          $validator->check('email', 'email');
          $validator->check('message', 'required');
          $validator->check('service', 'in', array_keys($emails));


          $errors = $validator->errors();

          // has errors
          if(! empty($errors))
          {
              Session::put('errors', $errors);
              Session::put('inputs', $_POST);
              header('Location: '. route('gk.service.form'));

          } else{

              // Email
              $message = $request->post('message');
              $service = $request->post('service');
              $email = $request->post('email');
              $name = $request->post('name');

              $headers = 'FROM: '. $email;
              $msg = '';

              if($emailSender->send($emails[$service], 'Formulaire de contact de '. $name, $message, $headers))
              {
                  $status = 1;
              }else{
                  $status = 0;
              }
              Session::put('success', $status);
              header('Location: '. route('gk.service.form')); // or to home page (app.home)
          }

          $form = new Form(Session::get('inputs'));
          return $this->render('form/index.php', compact('emails', 'form', 'msg'));
     }

}