<?php
class PropelMigration_1286483354
{
	// do nothing before structure change
	public function preUp($manager)
	{
	}

	// structure change (generated by Propel)
	public function getUpSQL()
	{
		return array('bookstore' => '
ALTER TABLE `book` ADD
(
	`author_id` INTEGER
);
//...
');
	}

	public function postUp($manager)
	{
		// post-migration code
		$sql = "INSERT INTO author (first_name,last_name) values('Leo','Tolstoi')";
		$pdo = $manager->getAdapterConnection('bookstore');
		$stmt = $pdo->prepare($sql);
		$stmt->execute();
	}
}

/*
Migrating Data

Propel generates the SQL code to alter the database structure, but your project may require more. For instance, in the newly added author table, the developer may want to add a few records.

That’s why Propel automatically executes the preUp() and postUp() migration before and after the structure migration. If you want to add data migration, that’s the place to put the related code.

Each of these methods receive a PropelMigrationManager instance, which is a good way to get PDO connection instances based on the buildtime configuration.

Here is an example implementation of data migration:

**/
