<div>
    <?php if(\Jan\Services\Session\Session::has('errors')): ?>
        <div class="alert alert-danger">
            <?= implode('<br>', \Jan\Services\Session\Session::get('errors'))?>
        </div>
    <?php endif; ?>

    <?php if(\Jan\Services\Session\Session::has('success')): ?>
        <div class="alert alert-success">
            Votre mail nous a bien ete envoye!
        </div>
    <?php endif; ?>

    <?php  # Get data from post
    $inputs = \Jan\Services\Session\Session::get('inputs');
    ?>
    <form action="<?= route('gk.service.form')?>" method="POST">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="input-name">Name</label>
                    <input type="text" name="name" class="form-control" placeholder="Enter your name..." id="input-name" value="<?= $inputs['name'] ?? null ?>" required>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="input-email">Email</label>
                    <input type="email" name="email" class="form-control" placeholder="Enter your email..." id="input-email" value="<?= $inputs['email'] ?? null ?>" required>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="input-service">Service</label>
                    <select name="service" id="input-service" class="form-control" required>
                        <option value="0"<?= isset($inputs['service']) && $inputs['service'] == 0 ? ' selected': ''?>>Contact</option>
                        <option value="1"<?= isset($inputs['service']) && $inputs['service'] == 1 ? ' selected': ''?>>Depannage</option>
                        <option value="2"<?= isset($inputs['service']) && $inputs['service'] == 2 ? ' selected': ''?>>Shell</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="input-message">Message</label>
                    <textarea name="message" id="input-message" class="form-control" placeholder="Type your message ..." required><?= $inputs['message'] ?? null ?></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </div>
        </div>
    </form>
    <h2>Debug: </h2>
    <?php dump(\Jan\Services\Session\Session::all()); ?>
    <?php
    \Jan\Services\Session\Session::remove('errors');
    \Jan\Services\Session\Session::remove('inputs');
    \Jan\Services\Session\Session::remove('success');
    ?>
</div>