<?php
namespace App\Entity;


/**
 * Class Post
 * @package App\Entity
 *
 * <Generated By JFramework>
*/
class Post
{

     /** @var int */
     private $id;


     /** @var string */
     private $title;


     /** @var string */
     private $body;



     /**
      * Post constructor.
     */
     public function __construct()
     {
     }


     /**
      * @return int
     */
     public function getId()
     {
         return $this->id;
     }


     /**
      * @return string
     */
     public function getTitle(): string
     {
         return $this->title;
     }


     /**
      * @param string $title
      * @return Post
     */
     public function setTitle(string $title): Post
     {
        $this->title = $title;
        return $this;
     }

    /**
     * @return null|string
     */
    public function getBody(): ?string
    {
        return $this->body;
    }

    /**
     * @param string $body
     * @return Post
     */
    public function setBody(?string $body): Post
    {
        $this->body = $body;
        return $this;
    }


}