<?php
namespace App\Entity;


/**
 * Class Post
 * @package App\Entity
 *
 * <Generated By JFramework>
*/
class Post
{

     /** @var int */
     private $id;


     /** @var string */
     private $title;


     /** @var string */
     private $content;


     /** @var array  */
     private $users = [];


     /**
      * Post constructor.
     */
     public function __construct()
     {
     }


     /**
      * @return int
     */
     public function getId()
     {
         return $this->id;
     }


     /**
      * @return string
     */
     public function getTitle(): string
     {
         return $this->title;
     }


     /**
      * @param string $title
      * @return Post
     */
     public function setTitle(string $title): Post
     {
        $this->title = $title;
        return $this;
     }


     /**
      * @return string
     */
     public function getContent(): string
     {
        return $this->content;
     }


     /**
      * @param string $content
      * @return Post
     */
     public function setContent(string $content): Post
     {
        $this->content = $content;
        return $this;
     }

     /**
      * @param User $user
     */
     public function addUser(User $user)
     {
         if(! \in_array($user, $this->users))
         {
             $this->users[] = $user;
             $user->addPost($this);
         }
     }


     /**
      * @return array
     */
     public function getUsers()
     {
         return $this->users;
     }
}