<?php
namespace App\Controllers;


use Jan\Component\Http\Request;
use Jan\Component\Http\Response;
use Jan\Component\Routing\Controller;


/**
 * Class DemoController
 * @package App\Controllers
 *
 * <Generated By JFramework>
*/
class DemoController extends Controller
{

     /**
      * @param Request $request
      * @return Response
     */
     public function index(Request $request): Response
     {
            return $this->render('demo/index.php');
     }
}